name: ROS TEST

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      ROS_CI_DESKTOP: "`lsb_release -cs`"  # e.g. [trusty|xenial|...]
      CI_SOURCE_PATH: $(pwd)
      ROSINSTALL_FILE: $CI_SOURCE_PATH/dependencies.rosinstall
      CATKIN_OPTIONS: $CI_SOURCE_PATH/catkin.options
      ROS_PARALLEL_JOBS: '-j8 -l6'
      # Set the python path manually to include /usr/-/python2.7/dist-packages
      # as this is where apt-get installs python packages.
      PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages
      ROS_DISTRO: melodic
    steps:
      - uses: actions/checkout@v1
      - name: Install ROS
        run: |
            ls -al ~/work/skyway_gw_controller_ros
            sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
            sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
            sudo apt update -qq
            sudo apt install -y dpkg
            sudo apt install -y ros-$ROS_DISTRO-desktop-full
            sudo apt install -y python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential
            source /opt/ros/$ROS_DISTRO/setup.bash
            # Prepare rosdep to install dependencies.
            sudo rosdep init
            rosdep update --include-eol-distros  # Support EOL distros.
      - name: build
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          catkin_make
          ls -al ~/catkin_ws/devel
          source devel/setup.bash
          cd ~/catkin_ws/src
          ln -s ~/work/skyway_gw_controller_ros/skyway_gw_controller_ros .
          ls -al
          cd skyway_gw_controller_ros
          pwd
          ls -al
          pip install -r requirements.txt
      - name: catkin_make run_tests
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          source ~/catkin_ws/devel/setup.bash
          cd ~/catkin_ws
          catkin_make run_tests
      - name: catkin_make test
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          source ~/catkin_ws/devel/setup.bash
          cd ~/catkin_ws
          catkin_make test

